# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dba816f63b96c532b4f017f12161ea01cf278b4ef80063e039c4715ccc6a98314e8bd10745dfa37364d3a6c2e18ad0c28bf8f6853ac212a9f0a547fa252b4560

test:
  secret_key_base: 28e7dc2f9fec9597370d919821988d98acd1ca62d857a8cf1d79b76f8b6b74b96f404122307e3bcffc260ffd4f13dae8ae6825e51ac9eebd16696c8375ea58f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
